name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload to Neocities
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
        run: |
          # Install curl
          sudo apt-get update && sudo apt-get install -y curl

          # Iterate all files in build/ and upload via Neocities API
          for file in $(find build -type f); do
            relative_path=${file#build/}
            echo "Uploading $relative_path"
            curl -X POST "https://neocities.org/api/upload" \
              -H "Authorization: Bearer $NEOCITIES_API_KEY" \
              -F "${relative_path}=@${file}"
          done
